/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import conexion.Conexion;
import java.io.File;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Castaño Moreno
 */
public class DBAdmin extends javax.swing.JFrame {

    static String user;
    static String pass;

    public DBAdmin(String User, String Pass) {
        this.user = User;
        this.pass = Pass;
        Conexion con = new Conexion(user, pass, "master");
        con.establecerConexion();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardarDB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMigrar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        FInicial = new com.toedter.calendar.JDateChooser();
        FFinal = new com.toedter.calendar.JDateChooser();
        btnFerreteriaDB = new javax.swing.JRadioButton();
        btnBodegaFerreteriaDB = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRestaurarDB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnFerreteriaDB1 = new javax.swing.JRadioButton();
        btnBodegaFerreteriaDB1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Acciones sobre DB");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Exportar archivo de copia de seguridad");

        btnGuardarDB.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardarDB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarDB.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarDB.setText("SELECCIONAR UBICACIÓN");
        btnGuardarDB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        btnGuardarDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Migrar de transaccional a bodega ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha Inicial");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha Final");

        btnMigrar.setBackground(new java.awt.Color(0, 153, 0));
        btnMigrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMigrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMigrar.setText("EJECUTAR");
        btnMigrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        btnMigrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMigrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMigrarActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(255, 102, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        FInicial.setDateFormatString("yyyy-MM-dd");
        FInicial.setMinSelectableDate(new java.util.Date(-62135747924000L));

        FFinal.setDateFormatString("yyyy-MM-dd");
        FFinal.setMinSelectableDate(new java.util.Date(-62135747924000L));

        buttonGroup1.add(btnFerreteriaDB);
        btnFerreteriaDB.setForeground(new java.awt.Color(0, 0, 0));
        btnFerreteriaDB.setText("FerreteriaDB");

        buttonGroup1.add(btnBodegaFerreteriaDB);
        btnBodegaFerreteriaDB.setForeground(new java.awt.Color(0, 0, 0));
        btnBodegaFerreteriaDB.setText("BodegaFerreteriaDB");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Seleccione base de datos");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Recuerda almacenarlo en una unidad extraible");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Restaurar DB desde un archivo.bak");

        btnRestaurarDB.setBackground(new java.awt.Color(0, 153, 0));
        btnRestaurarDB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRestaurarDB.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurarDB.setText("SLECCIONAR ARCHIVO");
        btnRestaurarDB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        btnRestaurarDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestaurarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarDBActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Seleccione base de datos");

        buttonGroup1.add(btnFerreteriaDB1);
        btnFerreteriaDB1.setForeground(new java.awt.Color(0, 0, 0));
        btnFerreteriaDB1.setText("FerreteriaDB");

        buttonGroup1.add(btnBodegaFerreteriaDB1);
        btnBodegaFerreteriaDB1.setForeground(new java.awt.Color(0, 0, 0));
        btnBodegaFerreteriaDB1.setText("BodegaFerreteriaDB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMigrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(btnRestaurarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnFerreteriaDB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBodegaFerreteriaDB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnFerreteriaDB1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBodegaFerreteriaDB1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBodegaFerreteriaDB)
                    .addComponent(btnFerreteriaDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBodegaFerreteriaDB1)
                    .addComponent(btnFerreteriaDB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestaurarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMigrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDBActionPerformed
        JFileChooser seleccion = new JFileChooser();

        int res = seleccion.showSaveDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File ruta = seleccion.getSelectedFile();

            if (btnFerreteriaDB.isSelected()) {
                Conexion con = new Conexion(user, pass, "master");
                con.establecerConexion();
                try {
                    String query = "EXEC sp_BACKUP '" + btnFerreteriaDB.getText() + "', '" + ruta + "'";
                    Statement st = con.conectar.createStatement();
                    st.execute(query);
                    JOptionPane.showMessageDialog(rootPane, "Copia almacenada en " + ruta + ".bak");
                } catch (Exception e) {
                    System.out.println(e);
                }
            }else if (btnBodegaFerreteriaDB.isSelected()) {
                Conexion con = new Conexion(user, pass, "master");
                con.establecerConexion();
                try {
                    String query = "EXEC sp_BACKUP '" + btnBodegaFerreteriaDB.getText() + "', '" + ruta + "'";
                    Statement st = con.conectar.createStatement();
                    st.execute(query);
                    JOptionPane.showMessageDialog(rootPane, "Copia almacenada en " + ruta + ".bak");
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }

    }//GEN-LAST:event_btnGuardarDBActionPerformed

    private void btnMigrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMigrarActionPerformed
        String FechaInicial = ((JTextField) FInicial.getDateEditor().getUiComponent()).getText();
        String FechaFinal = ((JTextField) FFinal.getDateEditor().getUiComponent()).getText();

        Conexion con = new Conexion(user, pass, "BodegaFerreteriaDB");
        con.establecerConexion();
        try {
            String query = "EXEC sp_ETL '" + FechaInicial + "', '" + FechaFinal + "' ";
            Statement st = con.conectar.createStatement();
            st.execute(query);
            JOptionPane.showMessageDialog(rootPane, "Transferencia correcta");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnMigrarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        InicioSesion ventana = new InicioSesion();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRestaurarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarDBActionPerformed
        JFileChooser seleccion = new JFileChooser();

        int res = seleccion.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File ruta = seleccion.getSelectedFile();

            if (btnFerreteriaDB1.isSelected()) {
                Conexion con = new Conexion(user, pass, "master");
                con.establecerConexion();
                try {
                    String query = "EXEC sp_RESTORE '" + btnFerreteriaDB1.getText() + "', '" + ruta + "' ";
                    Statement st = con.conectar.createStatement();
                    st.execute(query);
                    JOptionPane.showMessageDialog(rootPane, "La base de datos FerreteriaDB ha sido restaurada");
                } catch (Exception e) {
                    System.out.println(e);
                }
            }else if (btnBodegaFerreteriaDB1.isSelected()) {
                Conexion con = new Conexion(user, pass, "master");
                con.establecerConexion();
                try {
                    String query = "EXEC sp_RESTORE '" + btnBodegaFerreteriaDB1.getText() + "', '" + ruta + "' ";
                    Statement st = con.conectar.createStatement();
                    st.execute(query);
                    JOptionPane.showMessageDialog(rootPane, "La base de datos BodegaFerreteriaDB ha sido restaurada");
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btnRestaurarDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBAdmin(user, pass).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FFinal;
    private com.toedter.calendar.JDateChooser FInicial;
    private javax.swing.JRadioButton btnBodegaFerreteriaDB;
    private javax.swing.JRadioButton btnBodegaFerreteriaDB1;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JRadioButton btnFerreteriaDB;
    private javax.swing.JRadioButton btnFerreteriaDB1;
    private javax.swing.JButton btnGuardarDB;
    private javax.swing.JButton btnMigrar;
    private javax.swing.JButton btnRestaurarDB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
